development:
  adapter: postgresql
  encoding: unicode
  database: photo_sharing_development

test:
  adapter: postgresql
  encoding: unicode
  database: photo_sharing_test


production:
  adapter: postgresql
  encoding: unicode
  database: photo_sharing_production
